<?php //006f6
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Boniversum @version 4.1.1.0 PHP73 (03.01.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cP+JE0Z405FS6tNgN4ggL+yyHCKEMCGOfsEzEZ4vAonxMBCC1OruCe3w+o2FlN7cC8PIF+wR9
koGOuadgG4Cd8DD5m4YHIO1BbBZWitW4Z83zTrzoFcUsCFoKXAt29E+oI098xKQUG3GNacdCgcxU
bUH3zFgE4Ew4HTT774ECJH/gpEpyEQSXOSX9nBXZZHKnXr15hUSAlSSD2yaT5/VIxYigJvxFAAl0
M4biw5zMivj7LIRXzK58/50cp4blvUi9dxjvKr/sDe+6pk6tXV8UnlpJiKwiQUuZ4aec/S/kqpe0
9O/76DvJBsR6oI0sbHKxL4PEj30kbno2PlwoMM1ploAAi+rh1g5mM3kq7kfTPUU0UYf5KlYTUhXr
W4Q+VeUQGCrbkAzvQEzAe3k2fcKOheolO6k6nQwgR10OBNljzfbUcVFiKGkjUExHclrtYENT0OQh
vmFCsGqZKCny9eWRtnpQZi8cuUwgulAQK0moxQ8bkxX91LQVJJyxLN8miB7RMEE1kOoUStteTbKJ
i99vpD1ZKy23P5DkypAWeXuwGI+QkqIGsY+af9OrvC4gUAkzY5pWMAFxv3wXXowZYpb7YxCmdxYp
i75+o0==